### ISSUE TITLE
can enable stageless

### ISSUE THREAD

**Issue by zhangding222** [lovechoudoufu/cobaltstrike4.4_cdf#11]
Hi author, greate post!

can enable stageless？
https://wbglil.gitbook.io/cobalt-strike/cobalt-strikekuo-zhan/cs-bu-fen-gong-neng-qi-yong
<img width="906" alt="image" src="https://user-images.githubusercontent.com/42668898/164502525-7bfdd51f-05b1-4ae9-a501-81e73b08628e.png">

**Comment by lovechoudoufu** [comment]
看了下还是好改的  jar包扩展名改成zip 进去改一下cna就好，emmm自己手动改改吧

**Comment by zhangding222** [comment]
> 先把下还是好改的jar包扩展名自己改成zip进去改一下cna，emmm手动改一下吧

谢谢师傅
