### ISSUE TITLE
Read time out

### ISSUE THREAD

**Issue by getin63** [lovechoudoufu/cobaltstrike4.4_cdf#4]
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/39186999/161362433-8be6184a-9e37-4fb0-b8f3-c2ce9f3f5c86.png">
连接超时

**Comment by lovechoudoufu** [comment]
检查下是不是端口不通？

**Comment by getin63** [comment]
感谢师傅，我就是那个用户登录不上，加上服务器端口起不来。
