### ISSUE TITLE
上线内网主机时，执行命令，无回显。

### ISSUE THREAD

**Issue by G0rdita** [lovechoudoufu/cobaltstrike4.4_cdf#7]
大佬，使用4.4的cs时，在上线内网主机后，执行命令无回显，测试之前使用的cs是正常回显的。
![image](https://user-images.githubusercontent.com/40414497/162650308-7046a4ee-7f23-41af-a3a1-8b620d886c1e.png)

**Comment by lovechoudoufu** [comment]
last已经7h了  你这个机器已经掉线了吧

**Comment by G0rdita** [comment]
这个是早上起来截的图，我用我的cs4.4，同样的方法上线内网主机，是可以正常回显的。

**Comment by G0rdita** [comment]
不好意思，耽误时间了，乌龙了，我刚本地搭建了环境测试，正常显示。

**Comment by lovechoudoufu** [comment]
好的 那我关闭这个iss了 有其他问题可以再提
