### ISSUE TITLE
请教 官方解密key的来源与作用

### ISSUE THREAD

**Issue by winezer0** [lovechoudoufu/cobaltstrike4.4_cdf#8]
您好，我在readme中发现您描述了各个版本的官方解密key：
4.0 1be5be52c6255c33558e8a1cb667cb06
4.1 80e32a742060b884419ba0c171c9aa76
4.2 b20d487addd4713418f2d5a3ae02a7a0
4.3 3a4425490f389aeec312bdd758ad2b99
4.4 5e98194a01c6b48fa582a6a9fcbb92d6

同时在该key下又描述了 cobaltstrike.auth的认证密钥文件，rsa加密，解密内容。

但是在源码中,似乎cobaltstrike.auth的解密是由内置的公钥文件解密的,

是不是说这个官方解密key是用来解密cobaltstrike.auth的，并且是由内置公钥文件转变而来的？

**Comment by lovechoudoufu** [comment]
这个版本的官方解密key只是放在那的  和下面的rsa解密没关系，如你所说rsa解密使用的内置的密钥文件。
如图。例如4.3的key  其实对应的是rsa解密后内容的最后一段，是4.3版本/sleeve/中的dll文件的解密key
![image](https://user-images.githubusercontent.com/95681496/162859871-5d33d49a-958b-4bd4-a9ea-0c286bb0c062.png)
key带入方法进行解密的在这箭头指向的地方
![image](https://user-images.githubusercontent.com/95681496/162860077-33204e0a-f1d9-4fd7-a004-191050a615fa.png)


key转换成byte的代码：
```
import java.util.Arrays;

public class authTest {
    public byte[] intToByteArray(int num){
        return new byte[] {
                (byte) ((num >> 24) & 0xFF),
                (byte) ((num >> 16) & 0xFF),
                (byte) ((num >> 8) & 0xFF),
                (byte) (num & 0xFF)
        };
    }
    public static byte[] hex2bytes(String s) {
        int len = s.length();
        byte[] data = new byte[len / 2];
        for (int i = 0; i < len; i += 2) {
            data[i / 2] = (byte) ((Character.digit(s.charAt(i), 16) << 4) + Character.digit(s.charAt(i+1), 16));
        }
        return data;}

    public static void main(String[] args){
        authTest authTest = new authTest();
        int header = -889274157;
        int num = 29999999;
        int watermark = 1;

        byte[] bheader = authTest.intToByteArray(header);
        byte[] bnum = authTest.intToByteArray(num);
        byte[] bwatermark = authTest.intToByteArray(watermark);
        System.out.println(Arrays.toString(hex2bytes("3a4425490f389aeec312bdd758ad2b99")));

    }
}
```

**Comment by winezer0** [comment]
学到了，非常感谢您的热情指导
